apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: azurefile
  accessModes:
    - ReadWriteOnce
