apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: azurefile
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-vol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: az-vol
  template:
    metadata:
      labels:
        app: az-vol
    spec:
      volumes:
      - name: vol1
        persistentVolumeClaim: 
          claimName: claim1
      containers:
      - name: az-vol
        image: nginx:latest
        volumeMounts:
        - name: vol1
          mountPath: "/mnt/data"
        ports:
        - containerPort: 80